/// <reference types="vitest" />
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import react from '@vitejs/plugin-react';
import autoprefixer from 'autoprefixer';
import tailwindcss from 'tailwindcss';
import { defineConfig } from 'vite';
import checker from 'vite-plugin-checker';
import { VitePWA } from 'vite-plugin-pwa';
import tailwindConfig from './tailwind.config';

const here = path.dirname(fileURLToPath(import.meta.url));

// Session 111 — About TP Studio dialog needs build-time metadata
// (version, build date, copyright string). Read `package.json` once
// and compute the copyright years string from the current calendar
// year: "2026" through Dec 31 2026, then "2026–2027" from Jan 1 2027,
// "2026–2028" from Jan 1 2028, etc. Auto-rolls forward every January
// without any code edit — each new production build picks it up.
const pkg = JSON.parse(readFileSync(path.join(here, 'package.json'), 'utf8')) as {
  version: string;
};
const __APP_VERSION__ = pkg.version;
const __BUILD_DATE__ = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
const __COPYRIGHT_YEARS__ = (() => {
  const y = new Date().getFullYear();
  return y <= 2026 ? '2026' : `2026–${y}`;
})();

export default defineConfig(({ command }) => ({
  define: {
    __APP_VERSION__: JSON.stringify(__APP_VERSION__),
    __BUILD_DATE__: JSON.stringify(__BUILD_DATE__),
    __COPYRIGHT_YEARS__: JSON.stringify(__COPYRIGHT_YEARS__),
  },
  // Session 85 / #18 — vite-plugin-checker runs `tsc --noEmit` (and
  // Biome lint) in a worker alongside the dev server and surfaces
  // errors as a browser overlay. Without it, type errors are only
  // caught at `pnpm build` time (or by the editor's own tsserver,
  // which can lag). Dev-only — `pnpm build` already runs `tsc
  // --noEmit` ahead of `vite build`, so adding the checker plugin
  // there would just duplicate the work. The `command === 'serve'`
  // guard keeps the build step's plugin list untouched.
  plugins: [
    react(),
    ...(command === 'serve'
      ? [
          checker({
            typescript: true,
            biome: { command: 'check', flags: '' },
            // Overlay defaults to on; setting it explicit makes the
            // intent obvious and pins the contract if future plugin
            // versions flip the default.
            overlay: { initialIsOpen: false },
          }),
        ]
      : []),
    // Session 89 — PWA wiring. `registerType: 'prompt'` means we
    // surface an explicit "New version available" toast (via
    // `src/services/pwaUpdate.ts`) instead of force-reloading the
    // tab when a new SW lands. The precache glob covers every asset
    // type the build emits today (JS / CSS / HTML / icons / fonts);
    // `navigateFallback` makes the SW behave correctly for an SPA so
    // any deep link served by GitHub Pages falls back to index.html.
    // Dev-mode SW is disabled — the plugin's defaults caused a
    // confusing reload loop in earlier prototypes and we have no
    // reason to debug the SW flow during normal dev.
    VitePWA({
      registerType: 'prompt',
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,webp,ico,woff2}'],
        navigateFallback: '/index.html',
        navigateFallbackDenylist: [/^\/api\//],
      },
      manifest: {
        name: 'TP Studio',
        short_name: 'TP Studio',
        description:
          'Theory of Constraints diagramming tool — CRTs, FRTs, PRTs, TTs, Goal Trees, and Evaporating Clouds.',
        theme_color: '#6366f1',
        background_color: '#ffffff',
        display: 'standalone',
        orientation: 'any',
        start_url: '/',
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
          {
            src: '/icon-192-maskable.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'maskable',
          },
          {
            src: '/icon-512-maskable.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      devOptions: {
        enabled: false,
      },
    }),
  ],
  resolve: {
    alias: {
      '@': path.join(here, 'src'),
      // Session 89 — `virtual:pwa-register` is a virtual module
      // generated by `vite-plugin-pwa`; vitest's transform pipeline
      // can't resolve it during unit tests. Alias it to a small stub
      // in tests/ so the import resolves without dragging the real
      // SW registration code into jsdom.
      ...(process.env.VITEST
        ? { 'virtual:pwa-register': path.join(here, 'tests', 'stubs', 'virtual-pwa-register.ts') }
        : {}),
    },
  },
  css: {
    postcss: {
      plugins: [tailwindcss(tailwindConfig), autoprefixer()],
    },
  },
  build: {
    // Split heavy vendor libs into their own chunks so a feature commit
    // only invalidates one chunk's cache, and html-to-image (only used by
    // the PNG exporter) ships as a separate chunk that loads on demand.
    rollupOptions: {
      output: {
        manualChunks: {
          react: ['react', 'react-dom'],
          flow: ['@xyflow/react'],
          icons: ['lucide-react'],
          // Session 81 — `dagre` removed from the `flow` chunk so it can
          // be code-split. `useGraphPositions` now lazy-loads
          // `@/domain/layout` via `await import()`, which lets Rollup
          // place dagre in its own chunk that only loads when an
          // auto-layout diagram (non-EC) is first laid out. ~25 KB gzip
          // off the eager critical path.
        },
      },
    },
  },
  test: {
    environment: 'jsdom',
    globals: false,
    include: ['tests/**/*.test.ts', 'tests/**/*.test.tsx', 'src/**/*.test.ts', 'src/**/*.test.tsx'],
    // Session 84 — persist Vitest's transform cache across runs so the
    // dev-loop `pnpm test:watch` and the explicit `pnpm test` skip
    // recompiling unchanged files. ~50s cold run drops to ~5–10s warm.
    // The cache dir is gitignored alongside `dist/` and `coverage/`.
    cache: { dir: 'node_modules/.cache/vitest' },
    coverage: {
      // V8 is the bundled provider — no extra dep to install. JSON + text
      // covers both human reading and tooling consumers (codecov etc.).
      provider: 'v8',
      // `json-summary` produces `coverage/coverage-summary.json`, which
      // `scripts/pin-coverage-thresholds.mjs` reads to update the
      // measured floor. The plain `json` reporter (full details) is
      // kept for IDE consumers / external tools.
      reporter: ['text', 'json', 'json-summary', 'html'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.d.ts',
        'src/**/*.test.{ts,tsx}',
        'src/main.tsx', // entry shim — covered transitively
        'src/vite-env.d.ts',
      ],
      // Coverage thresholds are deliberately a *floor* — they fail CI
      // if coverage drops below these numbers. Workflow for tightening:
      //
      //   1. Run `pnpm test:coverage` locally.
      //   2. Read the bottom-of-output summary table (per-metric %).
      //   3. Replace the numbers below with (measured % − 2) so future
      //      drift is caught while leaving 2% slop for noise.
      //   4. Commit; CI now guards the new floor.
      //
      // Today's numbers are the conservative starting set — actual
      // measured coverage on a green run should exceed them. Bump after
      // the first CI run with `@vitest/coverage-v8` installed reports
      // the real baseline.
      thresholds: {
        // Session 81 re-pin. Session 80's `pdfExport.ts` added ~170
        // lines of DOM/canvas-touching code that jsdom can't exercise
        // (the pure helpers got their 13 unit tests; the rest is
        // covered by the Playwright e2e suite). Per the workflow
        // comment below — re-pinned at (measured − 2) for ~2% slop.
        lines: 65,
        statements: 65,
        functions: 63,
        branches: 76,
      },
    },
  },
}));
